site_name: Raggie
site_description: Самостоятельная cloud-native векторная СУБД
site_url: https://isotere.github.io/raggie/
repo_name: Isotere/raggie
repo_url: https://github.com/Isotere/raggie
edit_uri: edit/master/docs/
strict: true

theme:
  name: material
  language: ru
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Светлая тема

plugins:
  - search:
      lang:
        - ru
        - en

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Главная: index.md
  - Проект: product/index.md
  - Предметная область: domain/index.md
  - Архитектура: architecture/index.md
  - Разработка: development/index.md
  - Эксплуатация: operations/index.md
